auto: untarzanice | PLEASE review this commit @Thanatermesis

diff --git a/tree/usr/bin/elive-assistant b/tree/usr/bin/elive-assistant
--- a/tree/usr/bin/elive-assistant
+++ b/tree/usr/bin/elive-assistant
@@ -50,7 +50,7 @@ source /usr/share/elive-assistant/requests/requests
 # wrappers to allow both GUI and CLI
 #
 
-message_title="$( printf "$( eval_gettext "Supra-Intelligent AI for Elive" )" "" )"
+message_title="$( printf "$( eval_gettext "Supra-Intelligent Assistant for Elive" )" "" )"
 message_maybelater="$( printf "$( eval_gettext "Maybe Later" )" "" )"
 message_disable="$( printf "$( eval_gettext "Disable" )" "" )"
 
@@ -85,7 +85,7 @@ disable_autolaunchers(){
     if [[ -n "$EROOT" ]] ; then
         # e16
         if grep -qs "/elive-assistant-" "$HOME/.e16/startup-applications.list" ; then
-            if $guitool --question --title="$message_title" --text="$( eval_gettext "Do you want to disable the autorun of elive-assistant from your startup applications? It's basically a simple feature to give you a motivational sentence on your desktop startup and nothing more." )" --button="${message_disable}:0" and --button="${message_maybelater}:1" ; then
+            if $guitool --question --title="$message_title" --text="$( eval_gettext "Do you want to disable the autorun of elive-assistant from your startup applications? This feature is only about giving you a beautiful motivational quote on your desktop startup." )" --button="${message_disable}:0" and --button="${message_maybelater}:1" ; then
                 sed -i 's|^[^#].*/elive-assistant-|#&|g' "$HOME/.e16/startup-applications.list"
                 exit
             fi
@@ -331,15 +331,15 @@ chatgpt_apikey_get(){
     request_verification="Hello, how are you today? tell me something interesting in a one line sentence"
 
     # get key from web and insert it
-    if ! $guitool --question --title="$message_title" --text="$( eval_gettext "Elive made a tool to use AI features with ZERO tracking and only run when the user's wants it. Do you want to configure in order to enjoy these amazing features?" )" ; then
+    if ! $guitool --question --title="$message_title" --text="$( eval_gettext "This is a tool that gives you a good amount of useful features using AI, it only run when the user's wants it. Do you want to configure in order to enjoy these amazing features?" )" ; then
         disable_autolaunchers
         exit
     fi
-    $guitool --info --buton= --button=gtk-ok:0  --title="$message_title" --text="$( eval_gettext "In order to use this tool, you need to add an API key (cost-free). We will open a web page where you can generate a new API key, then copy the key and insert it in the next popup." )"
+    $guitool --info --buton= --button=gtk-ok:0  --title="$message_title" --text="$( eval_gettext "In order to use this tool, you need to add an API key. We will open a web page where you can generate a new API key, then copy the key and insert it in the next popup." )"
 
     ( web-launcher https://beta.openai.com/account/api-keys & )
     sleep 12
-    $guitool --info --buton= --button=gtk-ok:0  --title="$message_title" --text="$( eval_gettext "Instructions: First you need to Sign Up if you didn't do it yet. After, go to your account to view your API keys and then generate a new one; this key is what we need to communicate with the AI." )"
+    $guitool --info --buton= --button=gtk-ok:0  --title="$message_title" --text="$( eval_gettext "Instructions: First you need to Sign Up if you didn't do it yet. After, go to your account to view your API keys and then generate a new one; this key is what we need to communicate with the service." )"
     sleep 3
 
     result="$( $guitool --entry --title="$message_title" --text="$( eval_gettext "Insert your API key here" )" )"
@@ -369,7 +369,7 @@ chatgpt_apikey_get(){
         else
             local message_failed_response
             #message_failed_response="$( printf "$( eval_gettext "Failed verification response, AI answered '%s' and should have answered '%s'" )" "$verifier" "enlightenment" )"
-            message_failed_response="$( printf "$( eval_gettext "Failed verification response, the AI didn't reply anything." )" )"
+            message_failed_response="$( printf "$( eval_gettext "Failed verification response, we didn't received anything from the selected service." )" )"
 
             el_error_wrapper "$message_failed_response"
             exit 1
@@ -524,7 +524,7 @@ main(){
     if [[ -z "$conf_chatgpt_apikey" ]] ; then
         disable_autolaunchers
 
-        $guitool --error --title="$message_title" --text="$( eval_gettext "You need to insert a (cost-free) API key to use this tool. Exiting..." )"
+        $guitool --error --title="$message_title" --text="$( eval_gettext "You need to insert an API key to use this tool. Exiting..." )"
         exit 1
     fi
 
